name: todo
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  go_router: ^14.2.7
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.6.1
  flutter_svg: ^2.0.17
  # device_preview: ^1.2.0
  json_annotation: ^4.9.0
  logger: any #for logging purpose
  fpdart: ^1.1.1
  shared_preferences: ^2.2.2
  freezed_annotation: ^2.4.1

  expansion_tile_group: ^2.0.0
  flutter_bounce: ^1.1.0

  easy_debounce: ^2.0.3
  custom_refresh_indicator: ^4.0.1
  shimmer: ^3.0.0
  loader_overlay: ^5.0.0
  keyboard_actions: ^4.2.0
  extended_image: ^9.0.7

  intl: 0.19.0

  permission_handler: ^11.4.0

  #error
  talker: any
  talker_flutter: ^4.5.2
  talker_riverpod_logger: ^4.7.1

  #UI
  flash: ^3.1.1
  drift: ^2.15.0
  sqlite3_flutter_libs: ^0.5.18
  path_provider: ^2.0.15
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ">=2.3.0 <4.0.0"
  drift_dev: ^2.15.0
  flutter_lints: ^5.0.0
  freezed: ^2.4.5
  json_serializable: ^6.6.2
  retrofit_generator: ^9.1.7
  # melos: ^6.1.0
  riverpod_generator: ^2.4.0
  # riverpod_lint: ^2.3.10
  flutter_gen_runner: ^5.10.0

flutter:
  # generate: true
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/lottie/

flutter_gen:
  output: lib/generated/assets/

  integrations:
    image: true
    flutter_svg: true
    lottie: true
